### ISSUE TITLE
State of this repo

### ISSUE THREAD

**Issue by msvbg** [restitux/GameNetworkingSockets-rs#1]
Hi @restitux! Nice job getting the ball rolling with this library! I've peeked a little bit at the code, and it looks like you've gotten pretty far. What do you think the state of this code is in right now? How much work is needed to make it ready for use?

EDIT: I see now that you posted [this](https://github.com/restitux/steamworks-rs) in a [steamworks-rs thread](https://github.com/Noxime/steamworks-rs/issues/6), which is perhaps a better approach.

**Comment by restitux** [comment]
Your assessment is basically correct. The main thing left to figure out is how to get access to the event queue spmc sender handle in the library callbacks so we can bring those events into rust, which is critical for even basic operations like accepting a connection. 

I made an attempt at using libffi-rs for this which resulted in this issue: https://github.com/tov/libffi-rs/issues/48 . My current plan of attack once I get back to working on this is to just create a global HashMap that keeps track of all the queue and allows pushing.

**Comment by msvbg** [comment]
I found the whole steamworks-rs setup a little bit confusing and overcomplicated, and I'm now implementing my own bindings. Maybe I'll find that I need what was in steamworks-rs, but at least then I'll know why! I might publish my work if it turns out okay.
